// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */



 const sidebars = {
  // // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

tutorialSidebar: [
    'project_overview',
    'installation',
    'information_flow',
    {
      type: 'category',
      label: 'ChemSpace Actions',
      items: ['chemspace_docs/smiles_input','chemspace_docs/chemspace_actions'],
    },
    {
      type: 'category',
      label: 'ChemSpace Analysis Actions',
      items: ['chemspace_analysis/chemspace_analysis_actions'],
    },
    {
      type: 'category',
      label: 'MolDock Actions',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'MolDock Analysis Actions',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'MolDyn Actions',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'MolDyn Analysis Actions',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'Worked example',
      items: ['template_page'],
    },
    'contact',
  ],


};

export default sidebars;
