// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */



 const sidebars = {
  // // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

tutorialSidebar: [
    'project_overview',
    'installation',
    'information_flow',
    {
      type: 'category',
      label: 'ChemSpace',
      items: ['chemspace/compounds_input','chemspace/chemspace_generation'],
    },
    {
      type: 'category',
      label: 'ChemSpace Analysis',
      items: ['chemspace_analysis/chemspace_analysis'],
    },
    {
      type: 'category',
      label: 'MolDock',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'MolDock Analysis',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'MolDyn',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'MolDyn Analysis',
      items: ['template_page'],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ['examples/chemical_space_synthesis',
        'examples/docking', 
        'examples/ersilia_on_table',  
        'examples/molecules_preparation', 
        'examples/LA_Workshop',
        {
          type: 'category',
          label: 'LA Workshop',
          items: [
            'examples/LA_Workshop/introduction',
            'examples/LA_Workshop/design_of_TCIs_targeting_CZP',
            'examples/LA_Workshop/modeling_CZP_hCATl_binders',
            'examples/LA_Workshop/modeling_a_training_set',
            'examples/LA_Workshop/exploring_chemical_space',
            'examples/LA_Workshop/conclusions',
          ],
        },
      ],
    },
    'contact',
  ],


};

export default sidebars;
